document.write('  <!-- footer section starts -->');
document.write('');
document.write('  <section class="footer">');
document.write('');
document.write('    <div class="box-container">');
document.write('');
document.write('      <div class="box">');
document.write('        <h5>Quick Links</h5>');
document.write('        <a href="my-teams.html">Weave</a>');
document.write('        <a href="archive.html">Archive</a>');
document.write('        <a href="schedule.html">Schedule</a>');
document.write('        <a href="map.html">Map</a>');
document.write('      </div>');
document.write('');
document.write('      <div class="box">');
document.write('        <h5>Extra Links</h5>');
document.write('        <a href="my-page.html">My Page</a>');
document.write('        <a href="#">Ask Questions</a>');
document.write('        <a href="#">Terms of Use</a>');
document.write('        <a href="#">Privacy Policy</a>');
document.write('      </div>');
document.write('');
document.write('      <div class="box" id="contact">');
document.write('        <h5>Contact Info</h5>');
document.write('        <a href="#"> <i class=phone"></i> +123-456-7890 </a>');
document.write('        <a href="#"> <i class=phone"></i> +111-222-3333 </a>');
document.write('        <a href="#"> <i class=envelope"></i> weaveUMC@gmail.com </a>');
document.write('        <a href="#"> <i class=map"></i> UMC 2nd N-Dev </a>');
document.write('      </div>');
document.write('');
document.write('      <div class="box" id="follow">');
document.write('        <h5>Follow Us</h5>');
document.write('        <a href="#"> <i class="facebook"></i> facebook </a>');
document.write('        <a href="#"> <i class="twitter"></i> twitter </a>');
document.write('        <a href="#"> <i class="instagram"></i> instagram </a>');
document.write('        <a href="#"> <i class="linkedin"></i> linkedin </a>');
document.write('        <a href="#"> <i class="github"></i> github </a>');
document.write('      </div>');
document.write('');
document.write('    </div>');
document.write('');
document.write('    <div class="credit">created by <span>UMC Weave Team</span> | all rights reserved</div>');
document.write('');
document.write('  </section>');
document.write('');
document.write('  <!-- footer section ends -->');