document.write('<!DOCTYPE html>');
document.write('<html lang="en">');
document.write('');
document.write('<head>');
document.write('  <meta charset="UTF-8">');
document.write('  <meta http-equiv="X-UA-Compatible" content="IE=edge">');
document.write('  <meta name="viewport" content="width=device-width, initial-scale=1.0">');
document.write('  <title>🌊Weave</title>');
document.write('  <link rel="stylesheet" href="https://unpkg.com/swiper@7/swiper-bundle.min.css" />');
document.write('  <link rel="stylesheet" href="css/style.css">');
document.write('  <link rel="stylesheet" href="css/my-page.css">');
document.write('  <link rel="stylesheet" href="css/team-modal.css">');
document.write('</head>');
document.write('');
document.write('<body>');
document.write('  <!-- header starts -->');
document.write('  <header class="header">');
document.write('    <a href="my-teams.html" class="logo"> <i class=weave"></i> Weave </a>');
document.write('    <nav class="navbar">');
document.write('      <div id="nav-close" class=times"></div>');
document.write('      <a href="archive.html">Archive</a>');
document.write('      <a href="schedule.html">Schedule</a>');
document.write('      <a href="map.html">Map</a>');
document.write('    </nav>');
document.write('    <div class="icons">');
document.write('      <div id="menu-btn" class=bars"></div>');
document.write('      <button id="myBtn"><img width="20rem" src="icon/team-icon.png"></button>');
document.write('      <a href="my-page.html" class="myPage"><img width="20rem" src="icon/user-icon.png"></a>');
document.write('      <a href="#logout" class="logout"><img width="20rem" src="icon/logout-icon.png"></a>');
document.write('      <div id="search-btn" class=search"></div>');
document.write('    </div>');
document.write('  </header>');
document.write('');
document.write('  <!-- team modal -->');
document.write('  <div id="myModal" class="modal">');
document.write('    <div class="modal-content">');
document.write('      <div class="modal-header">');
document.write('        <span class="close">&times;</span>');
document.write('        <h2>Trip Crew Members</h2>');
document.write('      </div>');
document.write('      <div class="modal-body">');
document.write('        <img id="user-pic1" width="10rem" src="image/woman-profile1.png" alt=""> <p id="user-name1">user1</p>');
document.write('        <img id="user-pic2"width="10rem" src="image/woman-profile2.png" alt=""> <p id="user-name2">user2</p>');
document.write('        <img id="user-pic3"width="10rem" src="image/man-profile1.png" alt=""> <p id="user-name3">user3</p>');
document.write('        <img id="user-pic4"width="10rem" src="image/man-profile2.png" alt=""> <p id="user-name4">user4</p>');
document.write('      </div>');
document.write('      <div class="modal-footer">');
document.write(' <section class="invite">');
document.write('   <div class="content">');
document.write('     <h1 class="heading">Invite Trip Crew</h1>');
document.write('     <form action="">');
document.write('       <input type="email" name="" placeholder="type in email to invite trip member " id="" class="email">');
document.write('         <input type="submit" value="invite" class="btn">');
document.write('         </form>');
document.write('       </div>');
document.write('');
document.write('     </section>');
document.write('    </div>');
document.write('  </div>');
document.write('');
document.write('  <!--search form -->');
document.write('  <div class="search-form">');
document.write('    <div id="close-search" class=times"></div>');
document.write('    <form action="">');
document.write('      <input type="search" name="" placeholder="search here..." id="search-box">');
document.write('      <label for="search-box" class=search"></label>');
document.write('    </form>');
document.write('  </div>');
document.write('  <!-- header ends -->');
document.write('');
/*
document.write('  <!-- footer section starts -->');
document.write('');
document.write('  <section class="footer">');
document.write('');
document.write('    <div class="box-container">');
document.write('');
document.write('      <div class="box">');
document.write('        <h5>Quick Links</h5>');
document.write('        <a href="my-teams.html">Weave</a>');
document.write('        <a href="archive.html">Archive</a>');
document.write('        <a href="schedule.html">Schedule</a>');
document.write('        <a href="map.html">Map</a>');
document.write('      </div>');
document.write('');
document.write('      <div class="box">');
document.write('        <h5>Extra Links</h5>');
document.write('        <a href="my-page.html">My Page</a>');
document.write('        <a href="#">Ask Questions</a>');
document.write('        <a href="#">Terms of Use</a>');
document.write('        <a href="#">Privacy Policy</a>');
document.write('      </div>');
document.write('');
document.write('      <div class="box" id="contact">');
document.write('        <h5>Contact Info</h5>');
document.write('        <a href="#"> <i class=phone"></i> +123-456-7890 </a>');
document.write('        <a href="#"> <i class=phone"></i> +111-222-3333 </a>');
document.write('        <a href="#"> <i class=envelope"></i> weaveUMC@gmail.com </a>');
document.write('        <a href="#"> <i class=map"></i> UMC 2nd N-Dev </a>');
document.write('      </div>');
document.write('');
document.write('      <div class="box" id="follow">');
document.write('        <h5>Follow Us</h5>');
document.write('        <a href="#"> <i class="facebook"></i> facebook </a>');
document.write('        <a href="#"> <i class="twitter"></i> twitter </a>');
document.write('        <a href="#"> <i class="instagram"></i> instagram </a>');
document.write('        <a href="#"> <i class="linkedin"></i> linkedin </a>');
document.write('        <a href="#"> <i class="github"></i> github </a>');
document.write('      </div>');
document.write('');
document.write('    </div>');
document.write('');
document.write('    <div class="credit">created by <span>UMC Weave Team</span> | all rights reserved</div>');
document.write('');
document.write('  </section>');
document.write('');
document.write('  <!-- footer section ends -->');
*/
document.write('');
document.write('  <!-- external js file link -->');
document.write('  <script src="https://unpkg.com/swiper@7/swiper-bundle.min.js"></script>');
document.write('');
document.write('  <!-- custom js file link  -->');
document.write('  <script src="js/script.js"></script>');
document.write('</body>');
document.write('');
document.write('</html>');